### ISSUE TITLE
Mirror Threads?

### ISSUE THREAD

**Issue by YazzzMirror** [crimilo/Discord-Mirror#32]
Is there any way you can make it mirror newly created threads?

**Comment by crimilo** [comment]
There is currently no way to automatically mirror newly created threads. However you can do this manually by adding the thread to the list of mirrored channels, for example:

```yml
mirrors:
   1:
      channelIds:
         - "your_thread_channel_id_goes_here"
      webhookUrls:
         - "https://discord.com/api/webhooks/012345/abcdefg"
```
