### ISSUE TITLE
Role issues.

### ISSUE THREAD

**Issue by Jake10233** [crimilo/Discord-Mirror#33]
replacements:
         1:
            replace: "1178016101997744168"
            with: "1178563493901905920"
            where: "evereywhere"

Ive tried everything to make this work to replace the role with the updated one.

I tried <@&roleid> <@roleid> , roleid, nothing is working

**Comment by crimilo** [comment]
You should not be able to run the bot with this config, you have a typo.

This:
```yml
where: "evereywhere"
```
Should be:
```yml
where: "everywhere"
```

Assuming the role ids are correct, the rest is correct.

**Comment by Jake10233** [comment]
It is correct in the code. Role IDs are correct and still isnt working

**Comment by crimilo** [comment]
Send your config.yml here without your token.

**Comment by Jake10233** [comment]
# Status of the account that will mirror messages.
# Available options: online, offline, idle, dnd.
#
# Note that you should not be logged into the account
# when the bot starts for this option to take effect.
status: "online"

# Message sent in the console when a message is mirrored.
# You can set this to "" to disable it.
logMessage: "@%author%"

mirrors:
   # The following contains a mirror with its options.
   # Every option is optional and can be removed if not required.
   100:
      # You can find the id of a channel by enabling the Developer mode in your
      # Discord account settings and Right-Click -> Copy ID on a channel.
      channelIds:
         - "114898506993007371"
      # Webhooks are used to send mirrored messages to specific channels.
      # You can create a webhook for a channel with:
      # Edit channel -> Integrations -> Webhooks -> New webook.
      webhookUrls:
         - "https://discord.com/api/webhooks/"
      ignoredUserIds:
         - "insert_user_id_not_to_mirror_here"
      ignoredRoleIds:
         - "insert_role_id_not_to_mirror_here"
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: true
      # Replacements to perform before mirroring a message.
      # The where: option is used to specify which part of a message
      # should be replaced. The available options are:
      #
      # everywhere, message_content, embed_author, embed_author_url,
      # embed_author_icon_url, embed_title, embed_description, embed_url,
      # embed_field_name, embed_field_value, embed_image_url, embed_thumbnail_url
      # embed_footer, embed_footer_icon_url, embed_color.
      replacements:
         1:
            replace: "1093249651848790086"
            with: "1178563493901905920"
            where: "everywhere"
         # To replace mentions of @roles, @users or #channels,
         # you have to replace their ids. For example:
         # 2:
         #    replace: "insert_role_id_to_replace_here"
         #    with: "insert_replaced_role_id_here"
         #    where: "everywhere"
         #
         # To replace everything with a specific text, you can use the wildcard (*):
         # 3:
         #    replace: "*"
         #    with: "this_text_will_replace_everything"
         #    where: "everywhere"
   # You can create as many mirrors as you want, so that different
   # channels can be mirrored to different webhooks. For example:
   1  :
   # NFL Picks
      channelIds:
        - "1148985069093007371"
      webhookUrls:
        - "https://discord.com/api/webhooks/

**Comment by crimilo** [comment]
The replacements section is correct, however you have wrong webhook urls. Fix them.

This is an example valid webhook url:

https://discord.com/api/webhooks/1166408989215532200/dd3AGt7cdrgMTSZEuVbJDD3ahUgisPIT1T6j7aRFQvVC02aN6jr-0ko4GC17jCD1h

Use this and fix the webhook urls:

```yml
token: "your_token_here"
status: "online"
logMessage: "[%date%] Mirrored @%author%'s message from %server% #%channel%."
mirrors:
   1:
      channelIds:
         - "114898506993007371" # Make sure this channel ID is correct
      webhookUrls:
         - "https://discord.com/api/webhooks/" # This is not a valid webhook url. Fix it.
      replacements:
         1:
            replace: "1093249651848790086"
            with: "1178563493901905920"
            where: "everywhere"
   2:
      channelIds:
        - "1148985069093007371" # Make sure this channel ID is correct
      webhookUrls:
        - "https://discord.com/api/webhooks/" # This is not a valid webhook url. Fix it.
```
