### ISSUE TITLE
Double messages

### ISSUE THREAD

**Issue by YazzzMirror** [crimilo/Discord-Mirror#35]
Hello I've updated to the most recent version and for some reason still am getting double messages randomly. Not on all messages but only some

**Comment by YazzzMirror** [comment]
This is my setup currently and it is always sending 2 messages on every mirrored message it sends. Do i have it setup wrong?

```
status: "online"

logMessage: ""

mirrors:
   1:
      channelIds:
         - "926332823416233985"
      webhookUrls:
         - "https://canary.discord.com/api/webhooks/1180181137105109134/Y3_ufsgtU0pLFDG-e9fKnxABvdC7-m56R57BWrjspHGNyNThicpyrAwc5hRD2ksaXjtf"
      ignoredUserIds:
         - ""
      ignoredRoleIds:
         - ""
      requirements:
         minEmbedsCount: 1
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: false
         mirrorMessagesOnEdit: false
      replacements:
         1:
            replace: "<@&844917331528122368>"
            with: " "
            where: "everywhere"
```
