### ISSUE TITLE
How to setup multiple mirror channel and webhook

### ISSUE THREAD

**Issue by searingarrow** [crimilo/Discord-Mirror#72]
``
mirrors:
   1:
      channelIds:                                                                                    
         - "1207990725191536670" 
         - "1214368694638092428" 
      webhookUrls:                                                                                   
         - "https://canary.discord.com/api/webhooks/1254060811475746817/bQewxpxDKBGNKwNm5hp2WrYRUmHusYgYZy3XMjpHyCRX5xydcRA1hm04S7yfK1vlZ_BB" 
         - "https://discord.com/api/webhooks/1254060606903025764/OJ57Ae2gP0ujhATaBW29b15McP4EE3uACHB8I5pQvTWeWSHiSDQ_CbWtEp0Jljxf-F6O" 
`
   
The result is bot copy multiple channel chat to every webhook. How to copy multiple channel one direction from 1 channel to 1 webhook?

**Comment by crimilo** [comment]
Create multiple mirrors.

e.g.:

```yml
1:
   channelIds:
      - "..."
   webhookUrls:
      - "..."
2:
   channelIds:
      - "..."
   webhookUrls:
      - "..."
```
