### ISSUE TITLE
Errors mirroring multiple channels

### ISSUE THREAD

**Issue by theredimposter** [crimilo/Discord-Mirror#74]
I am currently having issues trying to mirror multiple channels.

Initially when I tried this using the following format, the script would mirror the channels successfully but it would mirror every message from each channel to ALL webhooks multiple times.

```
token: "cool token"                                                                           
status: "invisible"                                                                                          
logMessage: ""  
mirrors:
   1:
      channelIds:                                                                                         
         - "000001"
         - "000002"    
         - "00003"                                                             
         - "00004"                                                                                                                               
      webhookUrls:                                                                                        
         - "https://discord.com/api/webhooks/abc123/12345"                                                          
         - "https://discord.com/api/webhooks/abc123/12345"                                                                                                                                       
         - "https://discord.com/api/webhooks/abc12345/1234567"                                                          
         - "https://discord.com/api/webhooks/abc12345/1234567"   
      requirements:                                                                                       
         minEmbedsCount: 0                                                                                
         minContentLength: 0                                                                              
         minAttachmentsCount: 0                                                                           

      options:                                                                                            
         useWebhookProfile: false 
         removeAttachments: false                    
         mirrorMessagesFromBots: true 
         mirrorReplyMessages: true 
         mirrorMessagesOnEdit: true 
```

I then tried the following format that was suggested but to no avail. The script itself runs but it fails to mirror any messages.
```
token: "cool token"                                                                           
status: "invisible"                                                                                          
logMessage: ""  
mirrors:
   1:
      channelIds:                                                                                         
         - "000001"                                                                                                                             
      webhookUrls:                                                                                        
         - "https://discord.com/api/webhooks/abc123/12345"     
   2:
      channelIds:                                                                                         
         - "000002"                                                                                                                             
      webhookUrls:                                                                                        
         - "https://discord.com/api/webhooks/abc123/12345"                                                          
   3:
      channelIds:                                                                                         
         - "00003"                                                                                                                             
      webhookUrls:                                                                                        
         - "https://discord.com/api/webhooks/abc12345/1234567"     
   4:
      channelIds:                                                                                         
         - "00004"                                                                                                                             
      webhookUrls:                                                                                        
         - "https://discord.com/api/webhooks/abc12345/1234567"     
         
      requirements:                                                                                       
         minEmbedsCount: 0                                                                                
         minContentLength: 0                                                                              
         minAttachmentsCount: 0                                                                           

      options:                                                                                            
         useWebhookProfile: false 
         removeAttachments: false                    
         mirrorMessagesFromBots: true 
         mirrorReplyMessages: true 
         mirrorMessagesOnEdit: true 

```
I would like to know what I am doing wrong. Could the issue be that I am trying to mirror two channels to one webhook? I would like to mention that I did try to mess around with some settings and noticed that the script eventually did work when adding a filter for one channel where I only wanted to mirror a single person's messages. The issue with this case was that only that single channel was being mirrored while the others failed to.

Any help is appreciated!
