### ISSUE TITLE
Deleting instead of replacing

### ISSUE THREAD

**Issue by CryptoSalade** [crimilo/Discord-Mirror#76]
Hello. 
First thank fo you work.

I was wondering, how can i delete something instead of replacing it?

replacements:                                                                                       
         1:                                                                                               
            replace: "TEST"                                                       
            with: " ???? 3                                                            
            where: "everywhere"

**Comment by crimilo** [comment]
set `with:` to an empty string.

like this:

```yml
with: ""
```

**Comment by CryptoSalade** [comment]
How would it look like if i want to remove many #channel mentions in one message:

```
  2:                                                                                               
 replace: "13546579846,15468476251651,1321465451,14654654321"                                                     
 with: ""                                                          
 where: "everywhere"                                                                           
     
```

Can i seperate IDs with , to have them all replace at once?

**Comment by crimilo** [comment]
```
1:
   replace: "first"
   with: "example1"
   where: "everywhere"
2:
   replace: "second"
   with: "example2"
   where: "everywhere"
```
